"""flashcard words

Revision ID: 0cf42723f3cf
Revises: a41da1b0f10b
Create Date: 2025-12-01 21:34:42.793990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf42723f3cf'
down_revision: Union[str, Sequence[str], None] = 'a41da1b0f10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=False),
    sa.Column('example', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['cardDecks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'word', name='uq_flashcard_words_deck_word')
    )
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_words_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_example'), ['example'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_words_word'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_example'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_definition'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_deck_id'))

    op.drop_table('flashcard_words')
    # ### end Alembic commands ###
