"""create word_chain_table

Revision ID: 508493adde6c
Revises: da0543ae2a0d
Create Date: 2025-12-12 17:22:41.816480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508493adde6c'
down_revision: Union[str, Sequence[str], None] = 'da0543ae2a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'word_chain',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('used_word', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'used_word', name='uq_user_word_chain')
    )
    op.create_index(op.f('ix_word_chain_used_word'), 'word_chain', ['used_word'], unique=False)
    op.create_index(op.f('ix_word_chain_user_id'), 'word_chain', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_chain_user_id'), table_name='word_chain')
    op.drop_index(op.f('ix_word_chain_used_word'), table_name='word_chain')
    op.drop_table('word_chain')
    # ### end Alembic commands ###
