"""add wordle_stats

Revision ID: 540bf1beb09b
Revises: 1ba8bc26bc03
Create Date: 2025-12-05 14:31:01.683057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540bf1beb09b'
down_revision: Union[str, Sequence[str], None] = '1ba8bc26bc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wordle_wins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('wordle_losses', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('wordle_win_streak', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wordle_win_streak')
        batch_op.drop_column('wordle_losses')
        batch_op.drop_column('wordle_wins')

    # ### end Alembic commands ###
