"""your_message

Revision ID: 7ff2a0296676
Revises: 7712acaf18c8
Create Date: 2025-11-14 10:44:56.247850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff2a0296676'
down_revision: Union[str, Sequence[str], None] = '7712acaf18c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_word_lang', sa.String(length=2), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('random_word_lang')

    # ### end Alembic commands ###
