"""make migration

Revision ID: 8fd3039e2d3d
Revises: 
Create Date: 2025-12-19 14:43:06.544869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd3039e2d3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('random_word_lang', sa.String(length=2), server_default='en', nullable=False),
    sa.Column('theme', sa.String(length=20), server_default='arctic', nullable=False),
    sa.Column('wordle_game', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wordle_wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wordle_losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wordle_win_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('random_session_words', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cardDecks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='uq_card_decks_user_title')
    )
    with op.batch_alter_table('cardDecks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardDecks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardDecks_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardDecks_lang'), ['lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardDecks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardDecks_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('translate', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('lang', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_user_words_user_word')
    )
    with op.batch_alter_table('user_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_words_comment'), ['comment'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_words_lang'), ['lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_words_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_words_translate'), ['translate'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_words_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_words_word'), ['word'], unique=False)

    op.create_table('flashcard_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=False),
    sa.Column('example', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['cardDecks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'word', name='uq_flashcard_words_deck_word')
    )
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_words_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_example'), ['example'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_words_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_words_word'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_example'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_difficulty'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_definition'))
        batch_op.drop_index(batch_op.f('ix_flashcard_words_deck_id'))

    op.drop_table('flashcard_words')
    with op.batch_alter_table('user_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_words_word'))
        batch_op.drop_index(batch_op.f('ix_user_words_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_words_translate'))
        batch_op.drop_index(batch_op.f('ix_user_words_status'))
        batch_op.drop_index(batch_op.f('ix_user_words_lang'))
        batch_op.drop_index(batch_op.f('ix_user_words_comment'))

    op.drop_table('user_words')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('cardDecks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardDecks_user_id'))
        batch_op.drop_index(batch_op.f('ix_cardDecks_title'))
        batch_op.drop_index(batch_op.f('ix_cardDecks_lang'))
        batch_op.drop_index(batch_op.f('ix_cardDecks_description'))
        batch_op.drop_index(batch_op.f('ix_cardDecks_category'))

    op.drop_table('cardDecks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
