"""update session_words

Revision ID: b0673765611f
Revises: c3afefa5facd
Create Date: 2025-12-06 13:53:20.388401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0673765611f'
down_revision: Union[str, Sequence[str], None] = 'c3afefa5facd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_words', schema=None) as batch_op:
        batch_op.drop_column('last_review')

    # ### end Alembic commands ###
