"""add session_words

Revision ID: c3afefa5facd
Revises: 8b67e0b7f8fb
Create Date: 2025-12-06 11:52:16.337170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3afefa5facd'
down_revision: Union[str, Sequence[str], None] = '8b67e0b7f8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardDecks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=10), nullable=False, server_default='en'))
        batch_op.create_index(batch_op.f('ix_cardDecks_lang'), ['lang'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardDecks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardDecks_lang'))
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
